spring:
  application:
    name: order
  jpa:
    show-sql: true
  rabbitmq:
    addresses: 192.168.12.130
    username: guest
    password: guest
    port: 5672

# mysql 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8085
env:
  blibliABC
