spring:
  jpa:
    show-sql: true
  redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      password: 666666
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 5000
# mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
